platform :ios, '11.0'

target 'JXPagerViewExample-OC' do
pod 'JXPagingView/Pager', :path => '../../../JXPagingView'
pod 'JXCategoryView'
pod 'MJRefresh', '3.4.0'
pod 'FDFullscreenPopGesture', '1.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
    end
  end
end
