platform :ios, '8.0'

use_frameworks!
target 'JXPagingViewExample' do
pod 'JXPagingView/Paging', :path => '../../../JXPagingView'
pod 'MJRefresh', '3.4.0'
pod 'JXSegmentedView'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
    end
  end
end
